# https://github.com/rvva/nginx-prometheus-grafana
# Заменить сеть на нужную
version: '3.7.2'

services:
  # Заменить своим
  nginx:
    image: nginx:1.25.3-alpine3.18
    container_name: nginx-www
    volumes: 
      - ./html:/etc/nginx/html:rw
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    networks:
      - localhost
    ports:
      - 80:80
      

  # https://prometheus.io/docs/prometheus/latest/installation/
  prometheus:
    image: prom/prometheus:v2.45.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # chown -Rc 65534:65534 prometheus/data
      - ./prometheus/data:/prometheus
    container_name: prometheus
    networks:
      - localhost
    ports:
      - 9090:9090

  # https://github.com/nginxinc/nginx-prometheus-exporter
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    command:
      - --nginx.scrape-uri=http://nginx/stub_status
    expose: 
      - 9113
    networks:
      - localhost
    depends_on:
      - prometheus

  # https://github.com/martin-helmich/prometheus-nginxlog-exporter
  nginxlog-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1
    container_name: nginx-exporter
    volumes:
      - ./nginxlog_exporter/nginxlog_exporter.yml:/etc/prometheus/nginxlog_exporter.yml
      - ./nginx/log:/var/log/nginx
    command:
      - -config-file=/etc/prometheus/nginxlog_exporter.yml
    networks:
      - localhost
    ports:
      - 4040:4040
    

  # https://grafana.com/docs/grafana/latest/installation/docker/
  grafana:
    image: grafana/grafana:10.0.10
    container_name: grafana
    user: '472:0'
    depends_on:
      - prometheus
    volumes:
      # chown 472:0 -Rc grafana/data
      - ./grafana/data:/var/lib/grafana
    env_file:
      - .env
    networks:
      - localhost
    ports:
      - 3000:3000

networks:
    localhost:
        name: localhost
        external: false