# https://prometheus.io/docs/prometheus/latest/getting_started/

global:
  scrape_interval:     15s # По умолчанию парсинг каждые 15 секунд.

  # Метка для внешних систем (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Конфигурация с одним эндпоинтом - самим Prometheus
scrape_configs:
  # Добавляется как метка `job=<job_name>` для всех собранных временных рядов.
  - job_name: 'prometheus'

    # Парсинг каждые 5 секунд.
    scrape_interval: 5s

    static_configs:
    # prometheus
      - targets: ['localhost:9090']
    # prometheus-nginx-exporter
      - targets: ['nginx-prometheus-exporter:9113']
